GET http://localhost:3001/api/kata?nama=test5

###

POST http://localhost:3001/api/kata HTTP/1.1
Content-Type: application/json

{
  "nama":"test66",
  "arti":"memeriksa66"
}

###

PUT http://localhost:3001/api/kata/6 HTTP/1.1
Content-Type: application/json

{
  "nama":"test66",
  "arti":"memeriksa66"
}

###

DELETE  http://localhost:3001/api/kata/6 HTTP/1.1

###
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
  "username":"sunny",
  "password":"sunny123"
}

###
POST http://localhost:3001/api/register HTTP/1.1
Content-Type: application/json

{
  "username":"sunny",
  "password":"sunny123"
}